const START_TIMER = 'START_TIMER';
const RESTART_TIMER = 'RESTART_TIMER';
const ADD_SECOND = 'ADD_SECOND';
const ADD_FRAME = 'ADD_FRAME';
const REMOVE_FRAME = 'REMOVE_FRAME';


export { START_TIMER, RESTART_TIMER, ADD_SECOND, ADD_FRAME, REMOVE_FRAME };