const START_TIMER = 'START_TIMER';
const RESTART_TIMER = 'RESTART_TIMER';
const ADD_SECOND = 'ADD_SECOND';
const ADD_FRAME = 'ADD_FRAME';
const REMOVE_FRAME = 'REMOVE_FRAME';
const SET_WORK_DURATION = 'SET_WORK_DURATION';
const SET_SHORT_BREAK_DURATION = 'SET_SHORT_BREAK_DURATION';
const SET_LONG_BREAK_DURATION = 'SET_LONG_BREAK_DURATION';


export { 	START_TIMER, 
			RESTART_TIMER, 
			ADD_SECOND, 
			ADD_FRAME, 
			REMOVE_FRAME, 
			SET_WORK_DURATION, 
			SET_SHORT_BREAK_DURATION, 
			SET_LONG_BREAK_DURATION 
		};